#!/usr/bin/env bash
# Generates the Caddyfile for kfchess based on NUM_WORKERS from config.sh.
# Usage: ./generate-caddyfile.sh [--http-only] [--install]
#   --http-only: listen on :80 only (no TLS, no ACME) for pre-DNS testing
#   --install:   copy to /etc/caddy/Caddyfile and validate syntax
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/config.sh"

OUTPUT_FILE="$SCRIPT_DIR/Caddyfile"
HTTP_ONLY=false

# Parse flags
for arg in "$@"; do
    case "$arg" in
        --http-only) HTTP_ONLY=true ;;
    esac
done

# Build upstream list and per-worker route blocks
UPSTREAMS=""
SERVER_ROUTES=""
for i in $(seq 1 "$NUM_WORKERS"); do
    PORT=$((8000 + i))
    UPSTREAMS="${UPSTREAMS} 127.0.0.1:${PORT}"
    SERVER_ROUTES="${SERVER_ROUTES}
		@worker${i} query server=worker${i}
		reverse_proxy @worker${i} 127.0.0.1:${PORT}"
done
UPSTREAMS="${UPSTREAMS# }"  # trim leading space

# Site address: ":80" for http-only, domain name for production (auto-HTTPS)
if [[ "$HTTP_ONLY" == true ]]; then
    SITE_ADDRESS=":80"
    COMMENT="# HTTP-only mode (no TLS) — for testing before DNS cutover."
    WWW_BLOCK=""
else
    SITE_ADDRESS="${DOMAIN}"
    COMMENT="# Caddy handles TLS automatically via Let's Encrypt."
    WWW_BLOCK="www.${DOMAIN} {
	redir https://${DOMAIN}{uri} permanent
}

"
fi

cat > "$OUTPUT_FILE" << CADDY_EOF
# Kung Fu Chess - Caddyfile
# Auto-generated by generate-caddyfile.sh — do not edit manually.
#
${COMMENT}
# See docs/DEPLOYMENT.md for architecture details.

${WWW_BLOCK}${SITE_ADDRESS} {
	# ── Health check ─────────────────────────────────────────
	handle /caddy-health {
		respond "ok" 200
	}

	# ── API (routed by ?server= param, fallback round-robin) ─
	# Game REST endpoints redirect to ?server=workerN when the
	# game lives on another worker (307), similar to WS 4302.
	handle /api/* {${SERVER_ROUTES}
		reverse_proxy ${UPSTREAMS} {
			health_uri /health
			health_interval 5s
		}
	}

	# ── Game WebSocket (routed by ?server= param) ────────────
	# If ?server=workerN is present, route to that specific worker.
	# Otherwise, round-robin (which may redirect via close code 4302).
	handle /ws/game/* {${SERVER_ROUTES}
		reverse_proxy ${UPSTREAMS} {
			health_uri /health
			health_interval 5s
		}
	}

	# ── Lobby WebSocket (round-robin) ────────────────────────
	handle /ws/lobby/* {
		reverse_proxy ${UPSTREAMS} {
			health_uri /health
			health_interval 5s
		}
	}

	# ── Replay WebSocket (round-robin) ───────────────────────
	handle /ws/replay/* {
		reverse_proxy ${UPSTREAMS} {
			health_uri /health
			health_interval 5s
		}
	}

	# ── Static frontend assets ───────────────────────────────
	handle {
		root * ${DEPLOY_DIR}/client/dist

		@static path *.js *.css *.png *.jpg *.jpeg *.gif *.ico *.svg *.woff *.woff2 *.mp3 *.ogg
		header @static Cache-Control "public, max-age=31536000, immutable"

		try_files {path} /index.html
		file_server
	}
}
CADDY_EOF

if [[ "$HTTP_ONLY" == true ]]; then
    echo "Generated Caddyfile: $OUTPUT_FILE (${NUM_WORKERS} workers, HTTP-only mode)"
else
    echo "Generated Caddyfile: $OUTPUT_FILE (${NUM_WORKERS} workers)"
fi

# Install if requested
if [[ " $* " == *" --install "* ]]; then
    sudo cp "$OUTPUT_FILE" /etc/caddy/Caddyfile
    sudo caddy validate --config /etc/caddy/Caddyfile
    echo "Installed to /etc/caddy/Caddyfile"
fi
