#!/usr/bin/env bash
# Generates the Caddyfile for kfchess based on NUM_WORKERS from config.sh.
# Usage: ./generate-caddyfile.sh [--install]
#   --install: copy to /etc/caddy/Caddyfile and validate syntax
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/config.sh"

OUTPUT_FILE="$SCRIPT_DIR/Caddyfile"

# Build upstream list and per-worker route blocks
UPSTREAMS=""
GAME_WS_ROUTES=""
for i in $(seq 1 "$NUM_WORKERS"); do
    PORT=$((8000 + i))
    UPSTREAMS="${UPSTREAMS} 127.0.0.1:${PORT}"
    GAME_WS_ROUTES="${GAME_WS_ROUTES}
		@worker${i} query server=worker${i}
		reverse_proxy @worker${i} 127.0.0.1:${PORT}"
done
UPSTREAMS="${UPSTREAMS# }"  # trim leading space

cat > "$OUTPUT_FILE" << CADDY_EOF
# Kung Fu Chess - Caddyfile
# Auto-generated by generate-caddyfile.sh — do not edit manually.
#
# Caddy handles TLS automatically via Let's Encrypt.
# See docs/DEPLOYMENT.md for architecture details.

www.${DOMAIN} {
	redir https://${DOMAIN}{uri} permanent
}

${DOMAIN} {
	# ── Health check ─────────────────────────────────────────
	handle /caddy-health {
		respond "ok" 200
	}

	# ── API (round-robin to all workers) ─────────────────────
	handle /api/* {
		reverse_proxy ${UPSTREAMS} {
			health_uri /health
			health_interval 5s
		}
	}

	# ── Game WebSocket (routed by ?server= param) ────────────
	# If ?server=workerN is present, route to that specific worker.
	# Otherwise, round-robin (which may redirect via close code 4302).
	handle /ws/game/* {${GAME_WS_ROUTES}
		reverse_proxy ${UPSTREAMS} {
			health_uri /health
			health_interval 5s
		}
	}

	# ── Lobby WebSocket (round-robin) ────────────────────────
	handle /ws/lobby/* {
		reverse_proxy ${UPSTREAMS} {
			health_uri /health
			health_interval 5s
		}
	}

	# ── Replay WebSocket (round-robin) ───────────────────────
	handle /ws/replay/* {
		reverse_proxy ${UPSTREAMS} {
			health_uri /health
			health_interval 5s
		}
	}

	# ── Static frontend assets ───────────────────────────────
	handle {
		root * ${DEPLOY_DIR}/client/dist

		@static path *.js *.css *.png *.jpg *.jpeg *.gif *.ico *.svg *.woff *.woff2 *.mp3 *.ogg
		header @static Cache-Control "public, max-age=31536000, immutable"

		try_files {path} /index.html
		file_server
	}
}
CADDY_EOF

echo "Generated Caddyfile: $OUTPUT_FILE (${NUM_WORKERS} workers)"

# Install if requested
if [[ "${1:-}" == "--install" ]]; then
    sudo cp "$OUTPUT_FILE" /etc/caddy/Caddyfile
    sudo caddy validate --config /etc/caddy/Caddyfile
    echo "Installed to /etc/caddy/Caddyfile"
fi
